import sys
lines = []
lines.append("import { createContext, useContext, useState, useEffect, useCallback } from react;")
lines.append("import supabase from ../config/supabase;")
lines.append("const AuthContext = createContext(null);")
lines.append("export function AuthProvider({ children }) {")
lines.append("  const [currentUser, setCurrentUser] = useState(null);")
lines.append("  const [profile, setProfile] = useState(null);")
lines.append("  const [isAdmin, setIsAdmin] = useState(false);")
lines.append("  const [loading, setLoading] = useState(true);")
lines.append("  const [toasts, setToasts] = useState([]);")
lines.append("  const showToast = useCallback((msg, type) => {")
lines.append("    const t = type || info; const id = Date.now(); setToasts(p => [...p, {id,message:msg,type:t}]); setTimeout(() => setToasts(p => p.filter(x => x.id!==id)), 3000);")
lines.append("  }, []);")
lines.append("  const fetchProfile = useCallback(async (userId) => { const r = await supabase.from(profiles).select(*).eq(id,userId).single(); return r.data; }, []);")
lines.append("  useEffect(() => {")
lines.append("    (async () => { try { const {data:{session}} = await supabase.auth.getSession(); if(session&&session.user){setCurrentUser(session.user); const p=await fetchProfile(session.user.id); setProfile(p); setIsAdmin(p&&p.role===admin);} } catch(e){console.error(e)} finally{setLoading(false)} })();")
lines.append("    const {data:listener} = supabase.auth.onAuthStateChange(async (e,session)=>{ if(session&&session.user){setCurrentUser(session.user); const p=await fetchProfile(session.user.id); setProfile(p); setIsAdmin(p&&p.role===admin);} else {setCurrentUser(null);setProfile(null);setIsAdmin(false);} });")
lines.append("    return ()=>{ if(listener&&listener.subscription) listener.subscription.unsubscribe(); };")
lines.append("  }, [fetchProfile]);")
lines.append("  const register = async (username, password, name) => { const email = username + @campus.localhost; const {data,error} = await supabase.auth.signUp({email,password,options:{data:{name}}}); if(error){ if(error.message && (error.message.includes(already registered)||error.message.includes(already exists))) throw new Error(u8be5u8d26u53f7u5df2u88ab); throw error; } if(data.user){setCurrentUser(data.user); const p=await fetchProfile(data.user.id); setProfile(p); setIsAdmin(false);} showToast(u6ce8u518cu6210u529f); };")
lines.append("  const login = async (username, password) => { const email = username + @campus.localhost; const {data,error} = await supabase.auth.signInWithPassword({email,password}); if(error){ if(error.status===400) throw new Error(u8d26u53f7u6216u5bc6u7801u9519u8bef); throw error; } setCurrentUser(data.user); const p=await fetchProfile(data.user.id); setProfile(p); const admin=p&&p.role===admin; setIsAdmin(admin); showToast(admin ? u5df2u5207u6362u4e3au7ba1u7406u5458u8eab : u767bu5f55u6210u529f); };")
lines.append("  const logout = async () => { await supabase.auth.signOut(); setCurrentUser(null);setProfile(null);setIsAdmin(false); showToast(u5df2u9000u51fau767bu5f55); };")
lines.append("  const adminLogin = async (username, password) => { const email = username + @campus.localhost; const {data,error} = await supabase.auth.signInWithPassword({email,password}); if(error) throw new Error(u8d26u53f7u6216u5bc6u7801u9519u8bef); const p=await fetchProfile(data.user.id); if(!p||p.role!==admin){await supabase.auth.signOut(); throw new Error(u8be5u8d26u53f7u4e0du662fu7ba1u7406u5458);} setCurrentUser(data.user); setProfile(p); setIsAdmin(true); showToast(u5df2u5207u6362u4e3au7ba1u7406u5458u8eab); };")
lines.append("  const updateProfile = async (updates) => { if(!currentUser) return; const {data,error} = await supabase.from(profiles).update(updates).eq(id,currentUser.id).select().single(); if(error) throw error; setProfile(data); };")
lines.append("  const refreshProfile = async () => { if(!currentUser) return; const p = await fetchProfile(currentUser.id); setProfile(p); setIsAdmin(p&&p.role===admin); };")
lines.append("  const value = { currentUser, profile, isAdmin, loading, toasts, showToast, login, register, logout, adminLogin, updateProfile, refreshProfile };")
lines.append("  return React.createElement(AuthContext.Provider, { value }, children);")
lines.append("}")
lines.append("export function useAuth() {")
lines.append("  const ctx = useContext(AuthContext);")
lines.append("  if (!ctx) throw new Error(useAuth must be used within AuthProvider);")
lines.append("  return ctx;")
lines.append("}")

dest = r"C:\\Users\\付建康\\Documents\\Codex\\2026-06-06\\web-react-tailwind-css-leancloud-vercel\\campus-circle\\src\\context\\AuthContext.jsx"
with open(dest, "w", encoding="utf-8") as f:
    f.write("\\n".join(lines))
print("Written: " + str(len("\\n".join(lines))) + " chars")
